[project]
name = "rag-research-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.8.4",
    "faiss-cpu>=1.13.2",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "pypdf>=6.9.2",
    "ragas>=0.4.3",
    "sentence-transformers>=5.3.0",
    "tiktoken>=0.12.0",
]
